In [2]:
import numpy as np
# 1-D array
array_1D = np.array([1,2,3,4,5])
print("1D Array : ", array_1D)

1D Array :  [1 2 3 4 5]


In [3]:
#2D array
array_2D = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D Array :", array_2D)

2D Array : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
#3D array
array_3D = np.array([[1,2,3,4,5],[6,7,8,9,10],[4,5,6,7,2]])
print("3D Array :", array_3D)

3D Array : [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 4  5  6  7  2]]


In [5]:
#create an array with ones
array_ones = np.ones((2,4))
print("Array with ones :",array_ones)

Array with ones : [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
#create an array with zeros
array_zeros =np.zeros((3,3))
print ("Array with zeros:", array_zeros)

Array with zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#create an array with a particular range
array_range = np.arange(10)
print("array with a range:",array_range)

array with a range: [0 1 2 3 4 5 6 7 8 9]
